I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ch1_follow_jorunn.rpy", line 202, in script
    show grandpa neutral at left2 with (Pause(0.4), dissolve)
TypeError: 'tuple' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/ch1_follow_jorunn.rpy", line 202, in script
    show grandpa neutral at left2 with (Pause(0.4), dissolve)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1363, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\exports.py", line 1781, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 1548, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 2608, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 2518, in instantiate_transition
    trans = self.ongoing_transition[layer](
TypeError: 'tuple' object is not callable

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
HeartsDepthDEMO 1.3
Wed Feb 12 00:17:23 2025
