I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 424, in script
    if show_gross:
  File "game/script.rpy", line 424, in <module>
    if show_gross:
NameError: name 'show_gross' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 424, in script
    if show_gross:
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1842, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 424, in <module>
    if show_gross:
NameError: name 'show_gross' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
HeartsDepthDEMO 1.1
Wed Oct 23 23:15:24 2024
